2022-11-23 15:15:58 ERROR [main]: failed to upgrade telephone number 
java.lang.RuntimeException: wrong number tel
	at models.users.User.upgradeTel(User.java:42)
	at models.users.User.setTel(User.java:34)
	at models.users.User.main(User.java:53)
2022-11-23 15:42:46 ERROR [main]: failed to upgrade telephone number 
Error type: TOO_SHORT_AFTER_IDD. Phone number had an IDD, but after this was not long enough to be a viable phone number.
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:3287)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3122)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3112)
	at models.users.User.upgradeTel(User.java:41)
	at models.users.User.<init>(User.java:26)
	at dao.UsersDAO.getUser(UsersDAO.java:26)
	at dao.UsersDAO.findAllUsers(UsersDAO.java:61)
	at dao.UsersDAO.main(UsersDAO.java:75)
2022-11-23 15:45:49 ERROR [main]: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'admin' for key 'users.login_UNIQUE'
2022-11-23 15:47:16 ERROR [main]: failed to get all users
java.sql.SQLException: Column 'id_users' not found.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:584)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:851)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
	at dao.UsersDAO.getUser(UsersDAO.java:28)
	at dao.UsersDAO.findAllUsers(UsersDAO.java:61)
	at dao.UsersDAO.main(UsersDAO.java:75)
2022-11-23 15:48:02 ERROR [main]: failed to get all users
java.sql.SQLException: Column 'id_roles' not found.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:584)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:851)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
	at dao.UsersDAO.getUser(UsersDAO.java:29)
	at dao.UsersDAO.findAllUsers(UsersDAO.java:61)
	at dao.UsersDAO.main(UsersDAO.java:75)
2022-11-24 17:24:08 ERROR [main]: failed to find user by id ->7
java.sql.SQLException: Column 'ship_id' not found.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:584)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:851)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
	at dao.CruisesDAO.getCruise(CruisesDAO.java:25)
	at dao.PassengersDAO.getTicket(PassengersDAO.java:23)
	at dao.PassengersDAO.findTicketByUserId(PassengersDAO.java:58)
	at dao.PassengersDAO.main(PassengersDAO.java:70)
2022-11-24 17:28:56 ERROR [main]: failed to find ticket by user`s id ->7
java.sql.SQLException: Column 'ship_id' not found.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:584)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:851)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
	at dao.CruisesDAO.getCruise(CruisesDAO.java:25)
	at dao.PassengersDAO.getTicket(PassengersDAO.java:23)
	at dao.PassengersDAO.findTicketByUserId(PassengersDAO.java:58)
	at dao.PassengersDAO.main(PassengersDAO.java:70)
2022-11-24 18:21:16 ERROR [main]: failed to find price by ticket`s id ->1
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1345)
	at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1358)
	at com.mysql.cj.jdbc.ClientPreparedStatement.setInt(ClientPreparedStatement.java:1536)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setInt(HikariProxyPreparedStatement.java)
	at dao.CruisesDAO.getPriceOfCruise(CruisesDAO.java:65)
	at dao.PassengersDAO.lambda$updateNumberOfPassengers$0(PassengersDAO.java:75)
	at dao.DBManager.inTransaction(DBManager.java:57)
	at dao.PassengersDAO.updateNumberOfPassengers(PassengersDAO.java:70)
	at dao.PassengersDAO.main(PassengersDAO.java:98)
2022-11-26 17:14:30 ERROR [main]: failed to get cruises list
java.sql.SQLException: Column 'cruise_name' not found.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:584)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:896)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
	at dao.CruisesDAO.getCruise(CruisesDAO.java:26)
	at dao.CruisesDAO.findAllCruises(CruisesDAO.java:104)
	at dao.CruisesDAO.main(CruisesDAO.java:121)
2022-11-26 17:44:07 ERROR [main]: failed to check on existing  tel->8731273
java.sql.SQLException: Before start of result set
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:532)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1322)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:830)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
	at dao.UsersDAO.existTel(UsersDAO.java:206)
	at dao.UsersDAO.main(UsersDAO.java:216)
2022-11-26 17:48:48 ERROR [main]: failed to upgrade telephone number 
java.lang.RuntimeException: wrong number tel
	at models.users.User.updateTel(User.java:43)
	at services.SignUpValidator.validatePhoneNumber(Validator.java:63)
	at dao.UsersDAO.main(UsersDAO.java:218)
2022-11-26 17:51:43 ERROR [main]: failed to upgrade telephone number 
Error type: NOT_A_NUMBER. The phone number supplied was null.
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:3230)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3122)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3112)
	at models.users.User.updateTel(User.java:41)
	at services.SignUpValidator.validatePhoneNumber(Validator.java:63)
	at dao.UsersDAO.main(UsersDAO.java:218)
2022-11-26 18:15:31 ERROR [main]: failed to update telephone number ->62252039
java.lang.RuntimeException: wrong number tel
	at services.SignUpValidator.updateTel(Validator.java:83)
	at dao.UsersDAO.main(UsersDAO.java:218)
2022-11-26 18:17:51 ERROR [main]: failed to update telephone number ->3380662252039
java.lang.RuntimeException: wrong number tel
	at services.SignUpValidator.updateTel(Validator.java:83)
	at dao.UsersDAO.main(UsersDAO.java:218)
2022-11-26 18:19:49 ERROR [main]: failed to update telephone number ->3380662252039
java.lang.RuntimeException: wrong number tel
	at services.SignUpValidator.updateTel(Validator.java:83)
	at services.SignUpValidator.validatePhoneNumber(Validator.java:60)
	at dao.UsersDAO.main(UsersDAO.java:218)
2022-12-02 14:18:55 ERROR [main]: failed to update telephone number ->80662252039
java.lang.RuntimeException: phone number is wrong
	at services.SignUpValidator.updateTel(SignUpValidator.java:97)
	at Main.main(Main.java:5)
2022-12-02 14:22:16 ERROR [main]: failed to update telephone number ->80662252039
java.lang.RuntimeException: phone number is wrong
	at services.SignUpValidator.updateTel(SignUpValidator.java:95)
	at Main.main(Main.java:5)
2022-12-09 00:00:15 ERROR [main]: failed to get a ships count 
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1345)
	at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1358)
	at com.mysql.cj.jdbc.ClientPreparedStatement.setString(ClientPreparedStatement.java:1714)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setString(HikariProxyPreparedStatement.java)
	at dao.ShipsDAO.shipsNameExist(ShipsDAO.java:121)
	at dao.ShipsDAO.main(ShipsDAO.java:138)
2022-12-09 00:01:54 ERROR [main]: failed to get a ships count 
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1345)
	at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1358)
	at com.mysql.cj.jdbc.ClientPreparedStatement.setString(ClientPreparedStatement.java:1714)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setString(HikariProxyPreparedStatement.java)
	at dao.ShipsDAO.shipsNameExist(ShipsDAO.java:121)
	at dao.ShipsDAO.main(ShipsDAO.java:138)
2022-12-09 00:02:46 ERROR [main]: failed to get a ships count 
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1345)
	at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1358)
	at com.mysql.cj.jdbc.ClientPreparedStatement.setString(ClientPreparedStatement.java:1714)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setString(HikariProxyPreparedStatement.java)
	at dao.ShipsDAO.shipsNameExist(ShipsDAO.java:121)
	at dao.ShipsDAO.main(ShipsDAO.java:138)
2022-12-09 00:05:58 ERROR [main]: failed to get a ships count 
java.sql.SQLException: Can not issue executeUpdate() or executeLargeUpdate() with statements that produce result sets
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1038)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at dao.ShipsDAO.shipsNameExist(ShipsDAO.java:122)
	at dao.ShipsDAO.main(ShipsDAO.java:137)
2022-12-09 00:07:17 ERROR [main]: failed to get a ships count 
java.sql.SQLException: Can not issue executeUpdate() or executeLargeUpdate() with statements that produce result sets
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1038)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at dao.ShipsDAO.shipsNameExist(ShipsDAO.java:122)
	at dao.ShipsDAO.main(ShipsDAO.java:137)
2022-12-09 00:08:35 ERROR [main]: failed to get a ships count 
java.sql.SQLException: Before start of result set
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:532)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1322)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:830)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
	at dao.ShipsDAO.shipsNameExist(ShipsDAO.java:122)
	at dao.ShipsDAO.main(ShipsDAO.java:137)
2022-12-28 14:24:44 ERROR [main]: failed to update telephone number ->80664570941
java.lang.RuntimeException: phone number is wrong
	at services.SignUpValidator.updateTel(SignUpValidator.java:85)
	at services.SignUpValidator.main(SignUpValidator.java:94)
2023-01-12 18:24:34 ERROR [main]: failed to find paid tickets list
java.sql.SQLSyntaxErrorException: Unknown column 'paid' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at dao.TicketsDAO.findAllPaidTickets(TicketsDAO.java:78)
	at dao.TicketsDAO.main(TicketsDAO.java:165)
